### PR TITLE
New feature : now configure config.json from cli

### PR DESCRIPTION
**Pull request by ram2510**
Users can generate config.json and index.html files from the cli

### CODE REVIEW

**Comment by ram2510** [comment]
If you like republish the npm package

**Comment by YashMeh** [comment]
@ram2510 thanks for contributing and sorry for the delay :)
Can you provide some screenshots for what you have done ?

**Comment by ram2510** [comment]
Hey it is in the readme file I have provided gifs for that

**Comment by ram2510** [comment]
Now you can configure the config.json file in the terminal thus making the process easy and faster instead of configuring it manually by opening the 
panda

**Comment by YashMeh** [comment]
Nice :+1:

**Pull request merged**
